### ISSUE TITLE
哈哈。还想提个问题。有没有可能做成打开网页直接可以播放的那种。在线形式的也可以下载M3U用别的浏览器播放那样。

### ISSUE THREAD

**Issue by wyongmin** [Guovin/IPTV#578]
哈哈。还想提个问题。有没有可能做成打开网页直接可以播放的那种。在线形式的也可以下载M3U用别的浏览器播放那样。

**Comment by Guovin** [comment]
是有这个计划，包括接口管理等等，项目文件夹已经创建了https://github.com/Guovin/GTV-web

**Comment by wyongmin** [comment]
> 是有这个计划，包括接口管理等等，项目文件夹已经创建了https://github.com/Guovin/GTV-web

期待一下。
