### ISSUE TITLE
最近tvbox打开直播源都要加载好久～是因为result里面的结果太多了吗？

### ISSUE THREAD

**Issue by yeats1989523** [Guovin/IPTV#579]

**Comment by Guovin** [comment]
是加载菜单列表还是单个频道接口加载？

**Comment by yeats1989523** [comment]
> 是加载菜单列表还是单个频道接口加载？

在tvbox点击直播，然后菜单列表加载就一直转圈圈～

**Comment by Guovin** [comment]
直播源地址用的是哪个？github最好通过代理访问

**Comment by yeats1989523** [comment]
> 直播源地址用的是哪个？github最好通过代理访问

用了镜像的地址：https://ghp.ci/raw.githubusercontent.com/yeats1989523/TV/master/output/user_result.txt

**Comment by yeats1989523** [comment]
我现在在更新～这个文件暂时访问不了～我试试挂代理或者找个其他的镜像地址～感谢大佬～
